image: Visual Studio 2019

configuration:
  - Debug
  - Release

platform: x64

build:
  - cmake -DCMAKE_C_COMPILER=MSVC -DCMAKE_CXX_COMPILER=MSVC -S . -B build
  - cmake --build build --config $(configuration) -j 2

test_script:
  - ctest