language: cpp
sudo: false
dist: focal

matrix:
  include:
    - compiler: g++
      env: BUILD_TYPE=Release
    - compiler: g++
      env: BUILD_TYPE=Debug

script:
  - cmake --version
  - mkdir build
  - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=$BUILD_TYPE -S . -B build
  - cmake --build build -j 2
  - cd build  
  - ctest --output-on-failure
