language: cpp
sudo: false


matrix:
    include:
        - compiler: g++
          env: BUILD_TYPE=Release
        - compiler: g++
          env: BUILD_TYPE=Debug

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make -j2
  - ctest
