language: cpp
sudo: true
dist: focal

matrix:
  include:
    - compiler: g++
      env: BUILD_TYPE=Release
    - compiler: g++
      env: BUILD_TYPE=Debug COVERAGE=--coverage
      
before_install:
  - sudo apt-get install lcov

script:
  - cmake --version
  - mkdir build
  - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="$COVERAGE" -S . -B build
  - cmake --build build -j 2
  - cd build  
  - ctest --output-on-failure
  - if [[ "$COVERAGE" == "--coverage" ]]; then lcov --directory . --capture --output-file ../coverage.info; fi
  - if [[ "$COVERAGE" == "--coverage" ]]; then lcov --remove ../coverage.info 'usr/*' --output-file ../coverage.info; fi
  - if [[ "$COVERAGE" == "--coverage" ]]; then lcov --remove ../coverage.info '*/tests/*' --output-file ../coverage.info; fi
  - if [[ "$COVERAGE" == "--coverage" ]]; then bash <(curl -s https://codecov.io/bash); fi
