dictionaries:
  - en
  - en_GB

excluded_files:
  - ".typo-ci.yml"

spellcheck_filenames: true

excluded_words:
  # names
  - appveyor
  - conda
  - conda-forge
  - devnull
  - gtest
  - mjolnir
  - msvc
  - readthedocs
  - rtd
  - typoci
  # assembly
  - dil
  - eax
  - edx
  - rax
  - rdi
  - rdx
  - sete
  # common variable names
  - argc
  - rhs
  # keywords
  - alignas
  - constexpr
  - nullptr
  # std header
  - climits
  - cstddef
  - cstdint
  # other
  - cmdline
  # program and tool specific -------------------------------------------------
  # clang
  - CommentPragmas
  - fno-omit-frame-pointer
  - fno-sanitize-recover
  - fsanitize
  - fsanitize-memory-track-origins
  # clang-tidy
  - cppcoreguidelines-pro-bounds-pointer-arithmetic
  - cppcoreguidelines-pro-type-reinterpret-cast
  # cmake
  - cmakelang
  - ctest
  # compiler
  - pthread
  - werror
  - wextra
  - wmissing-braces
  - wpedantic
  - wshadow
  # cppcheck
  - cppcheck
  - cppcheck-dir
  - isrc
  - max-ctu-depth
  # doxygen
  - addtogroup
  - doxygen
  - tparam
  # python
  - isort 
  - pydocstyle
  - rglob
  # sphinx
  - toctree
