dictionaries:
  - en
  - en_GB

excluded_files:
  - ".typo-ci.yml"

spellcheck_filenames: true

excluded_words:
  # names
  - gtest
  - mjolnir
  - msvc
  - typoci
  # commands
  - ctest
  - pthread
  - werror
  - wextra
  - wmissing-braces
  - wpedantic
  - wshadow
  # common variable names
  - rhs
  
