name: mjolnir
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - black
  - flake8
  - isort
  - myst-parser
  - pydocstyle
  - pyyaml
  - pip
  - pydata-sphinx-theme
  - pip:
    - cmakelang
