name: CI

on: [push]

jobs:
  GCC_Ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [DEBUG, RELEASE]
    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      run:
        cmake \
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        -DCMAKE_C_COMPILER=gcc \
        -DCMAKE_CXX_COMPILER=g++ \
        -S . -B build
    - name: Build
      run: cmake --build build -j 2
    - name: Run tests
      run: |
        cd build  
        ctest  --output-on-failure

  Clang_Ubuntu:
    runs-on: ubuntu-latest
    include:
       - runs-on: ubuntu-latest
         compiler: clang
         clang: 12
    strategy:
      matrix:
        build_type: [DEBUG, RELEASE]
    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      run:
        cmake
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_CXX_COMPILER=clang++
        -S . -B build
    - name: Build
      run: cmake --build build -j 2
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

  MSVC_Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [DEBUG, RELEASE]
    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      shell: bash -l {0}
      run: |
        cmake \
        -DCMAKE_C_COMPILER=MSVC \
        -DCMAKE_CXX_COMPILER=MSVC \
        -S . -B build
    - name: Build
      run: cmake --build build --config ${{matrix.build_type}} -j 2
    - name: Run tests
      run: |
        cd build
        ctest -C ${{matrix.build_type}} --output-on-failure

  MinGW_Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [DEBUG, RELEASE]
    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      shell: bash -l {0}
      run: |
        cmake \
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
        -G "MinGW Makefiles" -S . -B build
    - name: Build
      run: cmake --build build -j 2
    - name: Run tests
      run: |
        cd build
        ctest  --output-on-failure
