name: GCC Ubuntu

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: [DEBUG, RELEASE]
    steps:
    - uses: actions/checkout@v2
    - name: Print
      run: echo ${{github.event_name}}
    - name: Run CMake
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -S . -B build
    - name: Build
      run: cmake --build build -j 2
    - name: Run tests
      run: |
        cd build  
        ctest
