name: MinGW Windows

on: [push]


jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [DEBUG, RELEASE]
    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -G "MinGW Makefiles" -S . -B build
    - name: Build
      run: cmake --build build
    - name: Run tests
      run: |
        cd build  
        ctest
