name: CI MSVC Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [DEBUG, RELEASE]
    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      shell: bash -l {0}
      run: |
        cmake \
        -DCMAKE_C_COMPILER=MSVC \
        -DCMAKE_CXX_COMPILER=MSVC \
        -S . -B build
    - name: Build
      run: cmake --build build --config ${{matrix.build_type}} -j 2
    - name: Run tests
      run: |
        cd build  
        ctest -C ${{matrix.build_type}} --output-on-failure
