name: Clang-Tidy V9

on: [push]

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install clang-tidy
      run: |
        sudo apt-get install clang-tidy-9
    - name: Run CMake
      run: |
        mkdir build
        cd build
        cmake \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_BUILD_TYPE=DEBUG \
        ..
    - name: List all checks
      run: |
        clang-tidy-9 --list-checks
    - name: Run clang-tidy
      run: |
        cd build
        run-clang-tidy-9 "(mjolnir/core|tests)" -quiet
