name: Cppcheck

on: [push]

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install cppcheck
      run: |
        sudo apt-get install cppcheck
    - name: Print cppcheck version
      run: |
        cppcheck --version
    - name: Run cppcheck with config file
      run: |
        cppcheck --project=.cppcheck --dump --error-exitcode=1
    - name: Run cppcheck with manual commands (temporary backup to test if the config file is set up correctly)
      run: |
        cppcheck -Isrc --enable=all --suppress=missingIncludeSystem --error-exitcode=1 --std=c++17 tests src
