name: Documentation

on: [push]
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: docs/rtd/environment.yml
        activate-environment: RTD
        auto-activate-base: false
    - name: Run doxygen
      run: |
        doxygen .doxyfile
