name: Documentation

on: [push]
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: docs/environment.yml
        activate-environment: RTD
        auto-activate-base: false
        #mamba-version: "*"

    - name: Print doxygen version
      shell: bash -l {0}
      run: |
        doxygen -v

    - name: Run doxygen
      shell: bash -l {0}
      run: |
        doxygen .doxyfile
