name: Version updated

on: [pull_request]

jobs:
  check_version_updated:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Update remote branches
      run: |
          git remote update origin --prune  
    - name: Check version number update
      run: |
          python3 python/check_version_update.py core ${{ github.head_ref }} ${{ github.base_ref }}

