name: Version updated

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened, ready_for_review]
    branches:
    - master

jobs:
  check_version_updated:
    if: |
      !contains(github.event.pull_request.labels.*.name, 'skip_version_update') &&
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install gitpython
      run: |
          pip install gitpython
    - name: Update remote branches
      run: |
          git remote update origin --prune
    - name: Check version number update
      run: |
          python3 python/check_version_update.py core ${{ github.head_ref }} ${{ github.base_ref }}

