name: Warnings MSVC Windows

on:
  push:
    branches:
      - master
  pull_request:
    #branches:
    #  - master
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [DEBUG, RELEASE]
    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      run: |
        cmake \
        -DCMAKE_C_COMPILER=MSVC \
        -DCMAKE_CXX_COMPILER=MSVC \
        -S . -B build
    - name: Build
      run: cmake --build build --config ${{matrix.build_type}} -j 2

