name: GCC Warnings Ubuntu

on: [push]


jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: [DEBUG, RELEASE]
    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      run: |
      cmake \
      -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
      -DCMAKE_C_COMPILER=gcc \
      -DCMAKE_CXX_COMPILER=g++ \
      -DMJOLNIR_CORE_ADDITIONAL_COMPILE_OPTIONS="-Werror" \
      -S . -B build
    - name: Build
      run: cmake --build build -j 2
