name: Warnings MSVC Windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    if: |
      github.event_name == 'push' ||      
      contains(github.event.pull_request.labels.*.name, 'CIrunerroronwarnings') ||
      (github.event.pull_request.draft == false && github.base_ref == 'master')
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      shell: bash -l {0}
      run: |
        cmake \
        -DCMAKE_C_COMPILER=MSVC \
        -DCMAKE_CXX_COMPILER=MSVC \
        -DMJOLNIR_CORE_ADDITIONAL_COMPILE_OPTIONS="//WX" \
        -S . -B build
    - name: Build
      run: cmake --build build --config RELEASE -j 2

