name: Warnings Clang Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    #branches:
    #  - master
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      run: |
        cmake \
        -DCMAKE_BUILD_TYPE=RELEASE \
        -DCMAKE_C_COMPILER=clang \
        -DCMAKE_CXX_COMPILER=clang++ \
        -DMJOLNIR_CORE_ADDITIONAL_COMPILE_OPTIONS="-Werror" \
        -S . -B build
    - name: Build
      run: cmake --build build -j 2
