name: No Warnings MinGW Windows

on:
  push:
    branches:
      - master
  pull_request:
    #branches:
    #  - master
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      shell: bash -l {0}
      run: |
        cmake \
        -DCMAKE_BUILD_TYPE=RELEASE \
        -DMJOLNIR_CORE_ADDITIONAL_COMPILE_OPTIONS="-Werror" \
        -G "MinGW Makefiles" -S . -B build
    - name: Build
      run: cmake --build build -j 2

